<?php

namespace NicholasCreativeMedia\FedExPHP\Ship;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'AdditionalLabelsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\AdditionalLabelsDetail',
            'Address' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Address',
            'AdrLicenseDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\AdrLicenseDetail',
            'AlcoholDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\AlcoholDetail',
            'AncillaryFeeAndTax' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\AncillaryFeeAndTax',
            'AssociatedShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\AssociatedShipmentDetail',
            'BinaryBarcode' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\BinaryBarcode',
            'BrokerDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\BrokerDetail',
            'CertificateOfOriginDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CertificateOfOriginDetail',
            'ClientDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ClientDetail',
            'CodAddTransportationChargesDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CodAddTransportationChargesDetail',
            'CodDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CodDetail',
            'CodReturnPackageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CodReturnPackageDetail',
            'CommercialInvoice' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CommercialInvoice',
            'CommercialInvoiceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CommercialInvoiceDetail',
            'Commodity' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Commodity',
            'CompletedCodDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedCodDetail',
            'CompletedEtdDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedEtdDetail',
            'CompletedHazardousPackageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedHazardousPackageDetail',
            'CompletedHazardousShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedHazardousShipmentDetail',
            'CompletedHazardousSummaryDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedHazardousSummaryDetail',
            'CompletedHoldAtLocationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedHoldAtLocationDetail',
            'CompletedPackageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedPackageDetail',
            'CompletedShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedShipmentDetail',
            'CompletedSmartPostDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedSmartPostDetail',
            'CompletedTagDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CompletedTagDetail',
            'ConfigurableLabelReferenceEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ConfigurableLabelReferenceEntry',
            'Contact' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Contact',
            'ContactAndAddress' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ContactAndAddress',
            'ContentRecord' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ContentRecord',
            'CurrencyExchangeRate' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CurrencyExchangeRate',
            'CustomDeliveryWindowDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomDeliveryWindowDetail',
            'CustomDocumentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomDocumentDetail',
            'CustomLabelBarcodeEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelBarcodeEntry',
            'CustomLabelBoxEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelBoxEntry',
            'CustomLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelDetail',
            'CustomLabelGraphicEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelGraphicEntry',
            'CustomLabelPosition' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelPosition',
            'CustomLabelTextBoxEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelTextBoxEntry',
            'CustomLabelTextEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomLabelTextEntry',
            'CustomerImageUsage' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomerImageUsage',
            'CustomerReference' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomerReference',
            'CustomerSpecifiedLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomerSpecifiedLabelDetail',
            'CustomsClearanceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomsClearanceDetail',
            'CustomsDeclarationStatementDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomsDeclarationStatementDetail',
            'CustomsOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\CustomsOptionDetail',
            'DangerousGoodsContainer' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DangerousGoodsContainer',
            'DangerousGoodsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DangerousGoodsDetail',
            'DangerousGoodsShippersDeclarationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DangerousGoodsShippersDeclarationDetail',
            'DangerousGoodsSignatory' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DangerousGoodsSignatory',
            'DateRange' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DateRange',
            'DeleteShipmentRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DeleteShipmentRequest',
            'DeleteTagRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DeleteTagRequest',
            'DeliveryOnInvoiceAcceptanceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DeliveryOnInvoiceAcceptanceDetail',
            'DestinationControlDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DestinationControlDetail',
            'Dimensions' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Dimensions',
            'DocTabContent' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DocTabContent',
            'DocTabContentBarcoded' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DocTabContentBarcoded',
            'DocTabContentZone001' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DocTabContentZone001',
            'DocTabZoneSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DocTabZoneSpecification',
            'DocumentFormatOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\DocumentFormatOptionsRequested',
            'EMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EMailDetail',
            'EMailLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EMailLabelDetail',
            'EMailRecipient' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EMailRecipient',
            'EdtCommodityTax' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EdtCommodityTax',
            'EdtExciseCondition' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EdtExciseCondition',
            'EdtTaxDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EdtTaxDetail',
            'EmailOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EmailOptionsRequested',
            'EtdDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\EtdDetail',
            'ExportDeclarationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ExportDeclarationDetail',
            'ExportDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ExportDetail',
            'ExpressFreightDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ExpressFreightDetail',
            'FreightAddressLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightAddressLabelDetail',
            'FreightBaseCharge' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightBaseCharge',
            'FreightGuaranteeDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightGuaranteeDetail',
            'FreightRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightRateDetail',
            'FreightRateNotation' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightRateNotation',
            'FreightShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightShipmentDetail',
            'FreightShipmentLineItem' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightShipmentLineItem',
            'FreightSpecialServicePayment' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\FreightSpecialServicePayment',
            'GeneralAgencyAgreementDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\GeneralAgencyAgreementDetail',
            'HazardousCommodityContent' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityContent',
            'HazardousCommodityDescription' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityDescription',
            'HazardousCommodityInnerReceptacleDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityInnerReceptacleDetail',
            'HazardousCommodityOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityOptionDetail',
            'HazardousCommodityPackagingDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityPackagingDetail',
            'HazardousCommodityPackingDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityPackingDetail',
            'HazardousCommodityQuantityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HazardousCommodityQuantityDetail',
            'HoldAtLocationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HoldAtLocationDetail',
            'HomeDeliveryPremiumDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\HomeDeliveryPremiumDetail',
            'InternationalControlledExportDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\InternationalControlledExportDetail',
            'InternationalTrafficInArmsRegulationsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\InternationalTrafficInArmsRegulationsDetail',
            'LabelSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\LabelSpecification',
            'LiabilityCoverageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\LiabilityCoverageDetail',
            'LicenseOrPermitDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\LicenseOrPermitDetail',
            'LinearMeasure' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\LinearMeasure',
            'Localization' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Localization',
            'Measure' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Measure',
            'Money' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Money',
            'NaftaCertificateOfOriginDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NaftaCertificateOfOriginDetail',
            'NaftaCommodityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NaftaCommodityDetail',
            'NaftaLowValueStatementDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NaftaLowValueStatementDetail',
            'NaftaProducer' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NaftaProducer',
            'NetExplosiveDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NetExplosiveDetail',
            'Notification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Notification',
            'NotificationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NotificationDetail',
            'NotificationParameter' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\NotificationParameter',
            'Op900Detail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Op900Detail',
            'OperationalInstruction' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\OperationalInstruction',
            'PackageBarcodes' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PackageBarcodes',
            'PackageOperationalDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PackageOperationalDetail',
            'PackageRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PackageRateDetail',
            'PackageRating' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PackageRating',
            'PackageSpecialServicesRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PackageSpecialServicesRequested',
            'Party' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Party',
            'Payment' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Payment',
            'Payor' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Payor',
            'PendingShipmentAccessDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PendingShipmentAccessDetail',
            'PendingShipmentAccessorDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PendingShipmentAccessorDetail',
            'PendingShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PendingShipmentDetail',
            'PendingShipmentProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PendingShipmentProcessingOptionsRequested',
            'PickupDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PickupDetail',
            'PrintedReference' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PrintedReference',
            'PriorityAlertDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\PriorityAlertDetail',
            'ProcessShipmentReply' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ProcessShipmentReply',
            'ProcessShipmentRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ProcessShipmentRequest',
            'ProcessTagReply' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ProcessTagReply',
            'ProcessTagRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ProcessTagRequest',
            'RadioactivityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RadioactivityDetail',
            'RadionuclideActivity' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RadionuclideActivity',
            'RadionuclideDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RadionuclideDetail',
            'RateDiscount' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RateDiscount',
            'Rebate' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Rebate',
            'RecipientCustomsId' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RecipientCustomsId',
            'RecommendedDocumentSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RecommendedDocumentSpecification',
            'RegulatoryLabelContentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RegulatoryLabelContentDetail',
            'RequestedPackageLineItem' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RequestedPackageLineItem',
            'RequestedShipment' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\RequestedShipment',
            'ReturnAssociationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ReturnAssociationDetail',
            'ReturnEMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ReturnEMailDetail',
            'ReturnInstructionsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ReturnInstructionsDetail',
            'ReturnShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ReturnShipmentDetail',
            'Rma' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Rma',
            'ShipmentAuthorizationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentAuthorizationDetail',
            'ShipmentConfigurationData' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentConfigurationData',
            'ShipmentDryIceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentDryIceDetail',
            'ShipmentDryIceProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentDryIceProcessingOptionsRequested',
            'ShipmentEventNotificationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentEventNotificationDetail',
            'ShipmentEventNotificationSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentEventNotificationSpecification',
            'ShipmentLegRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentLegRateDetail',
            'ShipmentManifestDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentManifestDetail',
            'ShipmentNotificationFormatSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentNotificationFormatSpecification',
            'ShipmentOperationalDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentOperationalDetail',
            'ShipmentRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentRateDetail',
            'ShipmentRating' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentRating',
            'ShipmentReply' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentReply',
            'ShipmentSpecialServicesRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShipmentSpecialServicesRequested',
            'ShippingDocument' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocument',
            'ShippingDocumentDispositionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentDispositionDetail',
            'ShippingDocumentEMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentEMailDetail',
            'ShippingDocumentEMailRecipient' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentEMailRecipient',
            'ShippingDocumentFormat' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentFormat',
            'ShippingDocumentPart' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentPart',
            'ShippingDocumentPrintDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentPrintDetail',
            'ShippingDocumentSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ShippingDocumentSpecification',
            'SignatureOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\SignatureOptionDetail',
            'SmartPostShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\SmartPostShipmentDetail',
            'SmartPostShipmentProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\SmartPostShipmentProcessingOptionsRequested',
            'StringBarcode' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\StringBarcode',
            'Surcharge' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Surcharge',
            'Tax' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Tax',
            'TaxpayerIdentification' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\TaxpayerIdentification',
            'TrackingId' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\TrackingId',
            'TransactionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\TransactionDetail',
            'UploadDocumentReferenceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\UploadDocumentReferenceDetail',
            'ValidateShipmentRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ValidateShipmentRequest',
            'ValidatedHazardousCommodityContent' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ValidatedHazardousCommodityContent',
            'ValidatedHazardousCommodityDescription' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ValidatedHazardousCommodityDescription',
            'ValidatedHazardousContainer' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\ValidatedHazardousContainer',
            'VariableHandlingChargeDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\VariableHandlingChargeDetail',
            'VariableHandlingCharges' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\VariableHandlingCharges',
            'Volume' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Volume',
            'Weight' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\Weight',
            'WebAuthenticationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\WebAuthenticationDetail',
            'WebAuthenticationCredential' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\WebAuthenticationCredential',
            'VersionId' => '\\NicholasCreativeMedia\\FedExPHP\\Ship\\StructType\\VersionId',
        );
    }
}
