<?php

namespace NicholasCreativeMedia\FedExPHP\Rate;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'AdditionalLabelsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\AdditionalLabelsDetail',
            'Address' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Address',
            'AlcoholDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\AlcoholDetail',
            'AncillaryFeeAndTax' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\AncillaryFeeAndTax',
            'BrokerDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\BrokerDetail',
            'CertificateOfOriginDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CertificateOfOriginDetail',
            'CleansedAddressAndLocationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CleansedAddressAndLocationDetail',
            'ClientDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ClientDetail',
            'CodAddTransportationChargesDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CodAddTransportationChargesDetail',
            'CodDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CodDetail',
            'CommercialInvoice' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CommercialInvoice',
            'CommercialInvoiceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CommercialInvoiceDetail',
            'CommitDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CommitDetail',
            'Commodity' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Commodity',
            'ConfigurableLabelReferenceEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ConfigurableLabelReferenceEntry',
            'ConsolidationKey' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ConsolidationKey',
            'Contact' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Contact',
            'ContactAndAddress' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ContactAndAddress',
            'ContentRecord' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ContentRecord',
            'CurrencyExchangeRate' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CurrencyExchangeRate',
            'CustomDeliveryWindowDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomDeliveryWindowDetail',
            'CustomDocumentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomDocumentDetail',
            'CustomLabelBarcodeEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelBarcodeEntry',
            'CustomLabelBoxEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelBoxEntry',
            'CustomLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelDetail',
            'CustomLabelGraphicEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelGraphicEntry',
            'CustomLabelPosition' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelPosition',
            'CustomLabelTextBoxEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelTextBoxEntry',
            'CustomLabelTextEntry' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomLabelTextEntry',
            'CustomerImageUsage' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomerImageUsage',
            'CustomerReference' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomerReference',
            'CustomerSpecifiedLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomerSpecifiedLabelDetail',
            'CustomsClearanceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomsClearanceDetail',
            'CustomsOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\CustomsOptionDetail',
            'DangerousGoodsContainer' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DangerousGoodsContainer',
            'DangerousGoodsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DangerousGoodsDetail',
            'DangerousGoodsShippersDeclarationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DangerousGoodsShippersDeclarationDetail',
            'DangerousGoodsSignatory' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DangerousGoodsSignatory',
            'DateRange' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DateRange',
            'DelayDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DelayDetail',
            'DeliveryOnInvoiceAcceptanceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DeliveryOnInvoiceAcceptanceDetail',
            'DestinationControlDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DestinationControlDetail',
            'Dimensions' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Dimensions',
            'Distance' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Distance',
            'DocTabContent' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocTabContent',
            'DocTabContentBarcoded' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocTabContentBarcoded',
            'DocTabContentZone001' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocTabContentZone001',
            'DocTabZoneSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocTabZoneSpecification',
            'DocumentFormatOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocumentFormatOptionsRequested',
            'DocumentLineItem' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\DocumentLineItem',
            'EMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\EMailDetail',
            'EdtCommodityTax' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\EdtCommodityTax',
            'EdtExciseCondition' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\EdtExciseCondition',
            'EdtTaxDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\EdtTaxDetail',
            'EtdDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\EtdDetail',
            'ExportDeclarationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ExportDeclarationDetail',
            'ExportDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ExportDetail',
            'ExpressFreightDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ExpressFreightDetail',
            'ExpressFreightDetailContact' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ExpressFreightDetailContact',
            'FlatbedTrailerDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FlatbedTrailerDetail',
            'FreightAddressLabelDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightAddressLabelDetail',
            'FreightBaseCharge' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightBaseCharge',
            'FreightCommitDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightCommitDetail',
            'FreightGuaranteeDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightGuaranteeDetail',
            'FreightRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightRateDetail',
            'FreightRateNotation' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightRateNotation',
            'FreightServiceCenterDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightServiceCenterDetail',
            'FreightShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightShipmentDetail',
            'FreightShipmentLineItem' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightShipmentLineItem',
            'FreightSpecialServicePayment' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\FreightSpecialServicePayment',
            'GeneralAgencyAgreementDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\GeneralAgencyAgreementDetail',
            'HazardousCommodityContent' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityContent',
            'HazardousCommodityDescription' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityDescription',
            'HazardousCommodityInnerReceptacleDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityInnerReceptacleDetail',
            'HazardousCommodityOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityOptionDetail',
            'HazardousCommodityPackagingDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityPackagingDetail',
            'HazardousCommodityPackingDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityPackingDetail',
            'HazardousCommodityQuantityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HazardousCommodityQuantityDetail',
            'HoldAtLocationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HoldAtLocationDetail',
            'HomeDeliveryPremiumDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\HomeDeliveryPremiumDetail',
            'InternationalControlledExportDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\InternationalControlledExportDetail',
            'InternationalTrafficInArmsRegulationsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\InternationalTrafficInArmsRegulationsDetail',
            'KeyValueDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\KeyValueDetail',
            'LabelSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\LabelSpecification',
            'LiabilityCoverageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\LiabilityCoverageDetail',
            'LinearMeasure' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\LinearMeasure',
            'Localization' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Localization',
            'Measure' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Measure',
            'Money' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Money',
            'NaftaCertificateOfOriginDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NaftaCertificateOfOriginDetail',
            'NaftaCommodityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NaftaCommodityDetail',
            'NaftaProducer' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NaftaProducer',
            'NetExplosiveDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NetExplosiveDetail',
            'Notification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Notification',
            'NotificationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NotificationDetail',
            'NotificationParameter' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\NotificationParameter',
            'Op900Detail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Op900Detail',
            'PackageRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PackageRateDetail',
            'PackageSpecialServicesRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PackageSpecialServicesRequested',
            'Party' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Party',
            'Payment' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Payment',
            'Payor' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Payor',
            'PendingShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PendingShipmentDetail',
            'PendingShipmentProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PendingShipmentProcessingOptionsRequested',
            'PickupDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PickupDetail',
            'PriorityAlertDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\PriorityAlertDetail',
            'RadioactivityDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RadioactivityDetail',
            'RadionuclideActivity' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RadionuclideActivity',
            'RadionuclideDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RadionuclideDetail',
            'RateDiscount' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RateDiscount',
            'RateReply' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RateReply',
            'RateReplyDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RateReplyDetail',
            'RateRequest' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RateRequest',
            'RatedPackageDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RatedPackageDetail',
            'RatedShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RatedShipmentDetail',
            'Rebate' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Rebate',
            'RecipientCustomsId' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RecipientCustomsId',
            'RecommendedDocumentSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RecommendedDocumentSpecification',
            'RegulatoryLabelContentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RegulatoryLabelContentDetail',
            'RequestedPackageLineItem' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RequestedPackageLineItem',
            'RequestedShipment' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\RequestedShipment',
            'ReturnAssociationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ReturnAssociationDetail',
            'ReturnEMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ReturnEMailDetail',
            'ReturnInstructionsDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ReturnInstructionsDetail',
            'ReturnShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ReturnShipmentDetail',
            'Rma' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Rma',
            'ServiceSubOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ServiceSubOptionDetail',
            'ShipmentAuthorizationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentAuthorizationDetail',
            'ShipmentConfigurationData' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentConfigurationData',
            'ShipmentDryIceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentDryIceDetail',
            'ShipmentDryIceProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentDryIceProcessingOptionsRequested',
            'ShipmentEventNotificationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentEventNotificationDetail',
            'ShipmentEventNotificationSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentEventNotificationSpecification',
            'ShipmentLegRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentLegRateDetail',
            'ShipmentNotificationFormatSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentNotificationFormatSpecification',
            'ShipmentRateDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentRateDetail',
            'ShipmentSpecialServicesRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentSpecialServicesRequested',
            'ShipmentVariationOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShipmentVariationOptionDetail',
            'ShippingDocumentDispositionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentDispositionDetail',
            'ShippingDocumentEMailDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentEMailDetail',
            'ShippingDocumentEMailRecipient' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentEMailRecipient',
            'ShippingDocumentFormat' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentFormat',
            'ShippingDocumentPrintDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentPrintDetail',
            'ShippingDocumentSpecification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\ShippingDocumentSpecification',
            'SignatureOptionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\SignatureOptionDetail',
            'SmartPostShipmentDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\SmartPostShipmentDetail',
            'SmartPostShipmentProcessingOptionsRequested' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\SmartPostShipmentProcessingOptionsRequested',
            'Surcharge' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Surcharge',
            'Tax' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Tax',
            'TaxpayerIdentification' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\TaxpayerIdentification',
            'TrackingId' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\TrackingId',
            'TransactionDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\TransactionDetail',
            'UploadDocumentReferenceDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\UploadDocumentReferenceDetail',
            'VariableHandlingChargeDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\VariableHandlingChargeDetail',
            'VariableHandlingCharges' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\VariableHandlingCharges',
            'Volume' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Volume',
            'Weight' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\Weight',
            'WebAuthenticationDetail' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\WebAuthenticationDetail',
            'WebAuthenticationCredential' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\WebAuthenticationCredential',
            'VersionId' => '\\NicholasCreativeMedia\\FedExPHP\\Rate\\StructType\\VersionId',
        );
    }
}
